
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AGIMaster.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Order
{

    public Order()
    {

        this.OrderProducts = new HashSet<OrderProduct>();

        this.AdminOrders = new HashSet<AdminOrder>();

        this.AdminOrders1 = new HashSet<AdminOrder>();

    }


    public int Id { get; set; }

    public string Comapny { get; set; }

    public string Pending { get; set; }

    public System.DateTime DateCreated { get; set; }



    public virtual ICollection<OrderProduct> OrderProducts { get; set; }

    public virtual ICollection<AdminOrder> AdminOrders { get; set; }

    public virtual ICollection<AdminOrder> AdminOrders1 { get; set; }

}

}
