
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AGIMaster.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Table
{

    public int Id { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string CompanyName { get; set; }

    public string CompanyAddress { get; set; }

    public string PrimaryContactName { get; set; }

    public string PrimaryEmailAddress { get; set; }

    public string PrimaryPhone { get; set; }

    public string SecondaryContactName { get; set; }

    public string SecondaryEmailAddress { get; set; }

    public string SecondaryPhone { get; set; }

    public string ShippingAddress { get; set; }

    public Nullable<System.DateTime> CreationDate { get; set; }

    public string Roles { get; set; }

}

}
