//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGIMaster.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Table
    {
        public int Id { get; set; }

        [Required]
        public string Username { get; set; }

        [Required]
        [ValidatePasswordLength]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        public string CompanyName { get; set; }

        [Required]
        public string CompanyAddress { get; set; }

        [Required]
        public string PrimaryContactName { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string PrimaryEmailAddress { get; set; }

        [Required]
        public string PrimaryPhone { get; set; }

        [Required]
        public string SecondaryContactName { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string SecondaryEmailAddress { get; set; }

        [Required]
        public string SecondaryPhone { get; set; }

        [Required]
        public string ShippingAddress { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
